export const INTERESTS = {
  god: "Walking My Dog",
  tarot: "Tarot Card Reading",
  theater: "Theater",
  vintage: "Vintage Fashion",
  couchsurfing: "Couchsurfing",
  voguing: "Voguing",
  hhour: "Happy Hour",
  petanque: "Petanque",
  tennis: "Tennis",
  rave: "Rave",
  tango: "Tango",
  foodie: "Foodie Tour",
  streetf: "Street Food",
  startups: "Start ups",
  sushi: "Sushi",
  sneakers: "Sneakers",
  sechand: "Second Hand apparel",
  trips: "Road Trips",
  snowboard: "Snowboarding",
  expo: "Exhibitions",
  ski: "Skiing",
  motorsports: "Motor sports",
  fest: "Festivals",
  tatoo: "Tattoos",
  esport: "E-Sports",
  motorcycles: "Motorcycles",
  cook: "Amateur Cook",
  active: "Activism",
  bbq: "BBQ",
  sail: "Sailing",
  xfit: "Crossfit",
  walk: "Walking",
  kpop: "K-Pop",
  read: "Reading",
  sports: "Sports",
  aquarium: "Aquarium",
  insta: "Instagram",
  hotsprings: "Hot Springs",
  photo: "Photography",
  club: "Clubbing",
  shop: "Shopping",
  brunch: "Brunch",
  escapeCafe: "Escape Cafe",
  collect: "Collecting",
  slam: "Slam Poetry",
  yoga: "Hot Yoga",
  meditate: "Meditation",
  basket: "Basketball",
  hockey: "Hockey",
  travel: "Travel",
  langxchange: "Language Exchange",
  socmedia: "Social Media",
  gym: "Gym",
  skincare: "Skin Care",
  movies: "Movies",
  homeWorkout: "Home Workout",
  running: "Running",
  standup: "Stand-up Poetry",
  coffee: "Coffee",
  signing: "Signing",
};

export const LIFESTYLE = [
  {
    id: "gender",
    name: "Show me",
    values: [
      { name: "Everyone", value: "all" },
      { name: "Men", value: "male" },
      { name: "Women", value: "female" },
    ],
  },
  {
    id: "communication",
    name: "Communication style",
    values: [
      { name: "", value: "undefined" },
      { name: "Big time texter", value: "bigText" },
      { name: "Video chatter", value: "video" },
      { name: "People caller", value: "call" },
      { name: "Bad texter", value: "badText" },
      { name: "Better in person", value: "inperson" },
    ],
  },
  {
    id: "drink",
    name: "Drink of choice",
    values: [
      { name: "", value: "undefined" },
      { name: "Wine", value: "wine" },
      { name: "Beer", value: "beer" },
      { name: "Cocktails", value: "cocktail" },
      { name: "Coffee", value: "coffee" },
      { name: "Lifetime teetotaler", value: "lifeSober" },
      { name: "Newly teetotaler", value: "newSober" },
    ],
  },
  {
    id: "mbti",
    name: "Personality type",
    values: [
      { name: "", value: "undefined" },
      { name: "ISTJ", value: "ISTJ" },
      { name: "ISFJ", value: "ISFJ" },
      { name: "ISTP", value: "ISTP" },
      { name: "ISFP", value: "ISFP" },
      { name: "INFJ", value: "INFJ" },
      { name: "INFP", value: "INFP" },
      { name: "INTJ", value: "INTJ" },
      { name: "INTP", value: "INTP" },
      { name: "ESTP", value: "ESTP" },
      { name: "ESFP", value: "ESFP" },
      { name: "ESTJ", value: "ESTJ" },
      { name: "ESFJ", value: "ESFJ" },
      { name: "ENTP", value: "ENTP" },
      { name: "ENFP", value: "ENFP" },
      { name: "ENTJ", value: "ENTJ" },
    ],
  },
  {
    id: "food",
    name: "Dietary preference",
    values: [
      { name: "", value: "undefined" },
      { name: "Vegan", value: "vegan" },
      { name: "Vegetarian", value: "vegetarian" },
      { name: "Flexitarian", value: "flexitarian" },
      { name: "Carnivore", value: "carnivore" },
      { name: "Omnivore", value: "omnivore" },
    ],
  },
  {
    id: "pets",
    name: "Pets",
    values: [
      { name: "", value: "undefined" },
      { name: "Cat lover", value: "cat" },
      { name: "Dog lover", value: "dog" },
      { name: "Snake lover", value: "reptile" },
      { name: "Frog lover", value: "amphibian" },
      { name: "Fish lover", value: "fish" },
      { name: "Pet-free", value: "petfree" },
      { name: "Loves all the pets", value: "allpets" },
    ],
  },
  {
    id: "social",
    name: "Social media",
    values: [
      { name: "", value: "undefined" },
      { name: "Influencer", value: "influencer" },
      { name: "Socially active", value: "active" },
      { name: "Off the grid", value: "offgrid" },
    ],
  },
  {
    id: "workout",
    name: "Workout",
    values: [
      { name: "", value: "undefined" },
      { name: "Gym rat", value: "gymRat" },
      { name: "Occasional fitness", value: "occasionally" },
      { name: "Never exercised", value: "never" },
    ],
  },
  {
    id: "edu",
    name: "Education",
    values: [
      { name: "", value: "undefined" },
      { name: "Bachelor degree", value: "bachelor" },
      { name: "High school", value: "highschool" },
      { name: "Master degree", value: "master" },
      { name: "Doctor", value: "phd" },
    ],
  },
  {
    id: "smoke",
    name: "Smoking",
    values: [
      { name: "", value: "undefined" },
      { name: "Social smoker", value: "social" },
      { name: "Smoker", value: "smoker" },
      { name: "Smoke when drinking", value: "whenDrink" },
      { name: "Non-smoker", value: "nonSmoker" },
    ],
  },
];
